version: '2'

services:
  resume:
    environment:
      - UPDATE_SECRET=changeme
    build: .
    container_name: resume
    ports:
      - 5001:5001
    volumes:
      # the json and jinja2 volumes overload what the Dockerfile inserts on build
      # to allow for local modifications and real-time development
      - ./resume.json:/resume/resume.json
      - ./resume.md.jinja2:/resume/resume.md.jinja2
      - app-volume:/pandoc
    restart: always
    networks:
      - resume_net
  pandoc:
    environment:
      - MYRESUME_HOST=resume:5001
      - UPDATE_SECRET=changeme
    build:
      context: pandoc-sidecar
      dockerfile: Dockerfile
    container_name: pandoc
    volumes:
      - app-volume:/pandoc
    restart: always
    networks:
      - resume_net

volumes:
     app-volume:

networks:
  resume_net:
    driver: bridge
