version: '2'

services:
  jenkins:
    restart: unless-stopped
    environment:
      - PLUGIN_MANAGER_TOOL_VERSION=1.1.0
      - JENKINS_VERSION=2.240
    image: jondkelley/demo-jenkins-config-as-code:latest
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - ./.jenkins/init_scripts/groovy/scripts/SystemFolder.groovy:/usr/share/jenkins/ref/init.groovy.d/jondkelley_resume.groovy
      - maven-repo:/root/.m2
    restart: always
    networks:
      - resume_net
  resume:
    restart: unless-stopped
    environment:
      - UPDATE_SECRET=changeme
    build: .
    container_name: resume
    ports:
      - 5001:5001
    volumes:
      # the json and jinja2 volumes overload what the Dockerfile inserts on build
      # to allow for local modifications and real-time development
      - ./resume.json:/resume/resume.json
      - ./resume.md.jinja2:/resume/resume.md.jinja2
      - app-volume:/pandoc
    restart: always
    networks:
      - resume_net
  pandoc:
    restart: unless-stopped
    environment:
      - MYRESUME_HOST=resume:5001
      - UPDATE_SECRET=changeme
    build:
      context: pandoc-sidecar
      dockerfile: Dockerfile
    container_name: pandoc
    volumes:
      - app-volume:/pandoc
    restart: always
    networks:
      - resume_net

volumes:
    maven-repo:
      driver: local
    app-volume:

networks:
  resume_net:
    driver: bridge