version: '2'

services:
  resume:
    build: .
    container_name: resume
    ports:
      - 5001:5001
    volumes:
      - ./myresume/resume.json:/resume.json
    restart: always
    networks:
      - resume_net

networks:
  resume_net:
    driver: bridge
