apiVersion: v1
kind: Service
metadata:
  name: jonk-resume-app
spec:
  externalTrafficPolicy: Local
  ports:
  - name: web
    port: 80
    targetPort: 5001
  selector:
    app: jonk-resume-app
  type: LoadBalancer
