name: resume.json valid
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify resume.json is valid JSON
        run: python -m json.tool < resume.json